<ControlScreenView>
    MDBoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: "Password Keeper"
            right_action_items:
                [
                ['sync', lambda x: root.controller.sync_control_user()],
                ['delete', lambda x: root.controller.remove_accounts()],
                ['plus', lambda x: root.show_dialogue_add_account()],
                ]


        MDScrollView:

            MDList:
                id: container_accounts



