<ControlScreenView>
    MDBoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: "Password Keeper"
            right_action_items:
                [
                ['delete', lambda x: root.controller.delete_account()],
                ['plus', lambda x: root.controller.add_account()],
                ]



        MDScrollView:

            MDList:
                id: container_accounts



