<ContentDialogueAddAccount>
    orientation: "vertical"
    spacing: "12dp"
    padding: "12dp"
    size_hint_y: None
    height: "285dp"

    MDTextField:
        id: dialogue_name_field
        hint_text: "Name"

    MDTextField:
        id: dialogue_username_field
        hint_text: "Username"

    MDTextField:
        id: dialogue_password_field
        hint_text: "Password"
        password: True

    MDTextField:
        id: dialogue_url_field
        hint_text: "Url"
